[build]
builder = "NIXPACKS"

[deploy]
startCommand = "apt-get update && apt-get install -y python3-pip && pip3 install --break-system-packages uvicorn==0.27.1 fastapi==0.110.0 python-dotenv==1.0.0 pydantic requests && export PATH=$PATH:/usr/local/bin && python3 -m uvicorn api:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
providers = ["python"]
installCommand = "pip install --break-system-packages -r requirements.txt"
